version: '3.8'
services:
  # Main App
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    env_file:
      - .env

  # MongoDB
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
    volumes:
      - my_mongodb_data:/data/db
    ports:
      - 27017:27017

volumes:
  my_mongodb_data:
    driver: local
